spring:
  datasource:
    url: jdbc:h2:mem:h2test
    username: sa
    password:
    platform: h2
    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema.sql
#    data: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
