spring:
  thymeleaf:
      encoding: utf-8
      cache: false
      mode: HTML5
  datasource:
      url: jdbc:mysql://localhost/renantang?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true