spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/renantang?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: root
